/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizDeckIdRouteImport } from './routes/quiz.$deckId'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as WordsDeckIdRouteImport } from './routes/words.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizDeckIdRoute = QuizDeckIdRouteImport.update({
  id: '/quiz/$deckId',
  path: '/quiz/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsDeckIdRoute = WordsDeckIdRouteImport.update({
  id: '/words/$deckId',
  path: '/words/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz/$deckId': typeof QuizDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/words/$deckId': typeof WordsDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz/$deckId': typeof QuizDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/words/$deckId': typeof WordsDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz/$deckId': typeof QuizDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/words/$deckId': typeof WordsDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz/$deckId' | '/study/$deckId' | '/words/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz/$deckId' | '/study/$deckId' | '/words/$deckId'
  id: '__root__' | '/' | '/quiz/$deckId' | '/study/$deckId' | '/words/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizDeckIdRoute: typeof QuizDeckIdRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
  WordsDeckIdRoute: typeof WordsDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$deckId': {
      id: '/quiz/$deckId'
      path: '/quiz/$deckId'
      fullPath: '/quiz/$deckId'
      preLoaderRoute: typeof QuizDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$deckId': {
      id: '/words/$deckId'
      path: '/words/$deckId'
      fullPath: '/words/$deckId'
      preLoaderRoute: typeof WordsDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizDeckIdRoute: QuizDeckIdRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
  WordsDeckIdRoute: WordsDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
